# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(null=True)),
                ('attribute1', models.CharField(max_length=300, null=True)),
                ('attribute2', models.CharField(max_length=300, null=True)),
                ('attribute3', models.CharField(max_length=300, null=True)),
                ('attribute4', models.CharField(max_length=300, null=True)),
                ('attribute5', models.CharField(max_length=300, null=True)),
                ('target', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
