# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170518_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackdata',
            old_name='genre',
            new_name='attribute6',
        ),
        migrations.AddField(
            model_name='hackdata',
            name='attribute7',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hackdata',
            name='left',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
